services:
  fx-dashboard:
    build: .
    ports:
      - "8501:8501"
    environment:
      - RAPIRA_URL=${RAPIRA_URL:-https://api.rapira.net/open/market/rates}
      - BITKUB_SERVER_TIME_URL=${BITKUB_SERVER_TIME_URL:-https://api.bitkub.com/api/servertime}
      - BITKUB_TICKER_URL=${BITKUB_TICKER_URL:-https://api.bitkub.com/api/market/ticker?sym=THB_USDT}
      - BITKUB_API_KEY=${BITKUB_API_KEY:-}
      - BITKUB_API_SECRET=${BITKUB_API_SECRET:-}
      - SUBTRACT_CONST=${SUBTRACT_CONST:-0.1}
      - DEFAULT_MARGIN=${DEFAULT_MARGIN:-3.5}
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped
